name: azkar
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  shared_preferences: ^2.1.1
  dartz: ^0.10.1
  get_it: ^7.6.0
  flutter_bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  vibration: ^1.7.4
  audioplayers: ^6.1.0
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.2.3
  permission_handler: ^10.4.1
  http: ^0.13.3
  connectivity_plus: ^3.0.5
  fluttertoast: ^8.2.8
  location: ^4.4.0
  geocoding: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_svg: ^2.0.4


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher.xml"

flutter:
  uses-material-design: true
  assets:
    - assets/images/reload.png
    - assets/images/ic_menu.svg
    - assets/images/baseline_error_24_white.svg
    - assets/images/baseline_settings_24.svg
    - assets/images/ic_baseline_check_circle_24.svg
    - assets/audio/light_button.mp3
    - assets/images/facebook.svg
    - assets/images/ic_launcher.xml
    - assets/images/ic_launcher.png
    - assets/images/ic_launcher_small.png

  fonts:
    - family: typesetting
      fonts:
        - asset: fonts/typesetting.ttf
    - family: alfont
      fonts:
        - asset: fonts/alfont_com_alfont_com_4_30.ttf
